//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLib {
    
    
    #region Component Designer generated code 
    public partial class CommunicationManager_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::ClassLib.@__CommunicationManager.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::ClassLib.CommunicationManager), typeof(global::ClassLib.CommunicationManager_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::ClassLib.CommunicationManager), typeof(global::ClassLib.CommunicationManager_))]
    internal sealed partial class @__CommunicationManager : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__CommunicationManager(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::ClassLib.@__CommunicationManager.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__CommunicationManager);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getClientInfo", "ClientInfo0", "()Lclasslib/ClientTopicsInfo;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getConfigurations", "Configurations1", "()Lclasslib/TopicsConfiguration;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "InitializeAsync", "InitializeAsync2", "()Lsystem/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "SendMessageAsync", "SendMessageAsync3", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/la" +
                        "ng/String;Ljava/lang/String;Ljava/lang/String;)Lsystem/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "SendStreamMessageAsync", "SendStreamMessageAsync4", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lsystem" +
                        "/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "SubscribeContentAsync", "SubscribeContentAsync5", "(Ljava/lang/String;Ljava/lang/String;)Lsystem/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "UnsubscribeContentAsync", "UnsubscribeContentAsync6", "(Ljava/lang/String;Ljava/lang/String;)Lsystem/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "AddNewSubscriptionClient", "AddNewSubscriptionClient7", "(Ljava/lang/String;Ljava/lang/String;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "RemoveStreamingSubscriptionClientAsync", "RemoveStreamingSubscriptionClientAsync8", "(Ljava/lang/String;Ljava/lang/String;)Lsystem/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "InitLogSystem", "InitLogSystem9", "()V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "InitLogSystem", "InitLogSystem10", "(Ljava/lang/String;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "BaseTopicToId", "BaseTopicToId11", "(Ljava/lang/String;)Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorCommunicationManager0", "__ctorCommunicationManager0", "(Lnet/sf/jni4net/inj/IClrProxy;Ljava/lang/String;Lclasslib/TopicsConfiguration;Lc" +
                        "lasslib/ICommunicationManagerCallbacks;)V"));
            return methods;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle ClientInfo0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lclasslib/ClientTopicsInfo;
            // ()LClassLib/ClientTopicsInfo;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ClassLib.CommunicationManager @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ClassLib.CommunicationManager>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ClassLib.ClientTopicsInfo>(@__env, @__real.ClientInfo);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Configurations1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lclasslib/TopicsConfiguration;
            // ()LClassLib/TopicsConfiguration;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ClassLib.CommunicationManager @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ClassLib.CommunicationManager>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::ClassLib.TopicsConfiguration>(@__env, @__real.Configurations);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle InitializeAsync2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lsystem/Object;
            // ()LSystem/Threading/Tasks/Task;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ClassLib.CommunicationManager @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ClassLib.CommunicationManager>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Threading.Tasks.Task>(@__env, @__real.InitializeAsync());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle SendMessageAsync3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle messageId, global::net.sf.jni4net.utils.JniLocalHandle messageType, global::net.sf.jni4net.utils.JniLocalHandle infoIdentifier, global::net.sf.jni4net.utils.JniLocalHandle toID, global::net.sf.jni4net.utils.JniLocalHandle dataFormat, global::net.sf.jni4net.utils.JniLocalHandle content, global::net.sf.jni4net.utils.JniLocalHandle priority) {
            // (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lsystem/Object;
            // (LSystem/String;LSystem/String;LSystem/String;LSystem/String;LSystem/String;LSystem/String;LSystem/String;)LSystem/Threading/Tasks/Task;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ClassLib.CommunicationManager @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ClassLib.CommunicationManager>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Threading.Tasks.Task>(@__env, @__real.SendMessageAsync(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, messageId), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, messageType), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, infoIdentifier), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, toID), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, dataFormat), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, content), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, priority)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle SendStreamMessageAsync4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle contentIdentification, global::net.sf.jni4net.utils.JniLocalHandle dataFormat, global::net.sf.jni4net.utils.JniLocalHandle msgContent, global::net.sf.jni4net.utils.JniLocalHandle priority) {
            // (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lsystem/Object;
            // (LSystem/String;LSystem/String;LSystem/String;LSystem/String;)LSystem/Threading/Tasks/Task;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ClassLib.CommunicationManager @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ClassLib.CommunicationManager>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Threading.Tasks.Task>(@__env, @__real.SendStreamMessageAsync(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, contentIdentification), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, dataFormat), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, msgContent), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, priority)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle SubscribeContentAsync5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle contentIndentification, global::net.sf.jni4net.utils.JniLocalHandle streamerID) {
            // (Ljava/lang/String;Ljava/lang/String;)Lsystem/Object;
            // (LSystem/String;LSystem/String;)LSystem/Threading/Tasks/Task;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ClassLib.CommunicationManager @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ClassLib.CommunicationManager>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Threading.Tasks.Task>(@__env, @__real.SubscribeContentAsync(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, contentIndentification), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, streamerID)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle UnsubscribeContentAsync6(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle contentIndentification, global::net.sf.jni4net.utils.JniLocalHandle streamerID) {
            // (Ljava/lang/String;Ljava/lang/String;)Lsystem/Object;
            // (LSystem/String;LSystem/String;)LSystem/Threading/Tasks/Task;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ClassLib.CommunicationManager @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ClassLib.CommunicationManager>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Threading.Tasks.Task>(@__env, @__real.UnsubscribeContentAsync(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, contentIndentification), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, streamerID)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void AddNewSubscriptionClient7(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle priorityId, global::net.sf.jni4net.utils.JniLocalHandle subscriptionName) {
            // (Ljava/lang/String;Ljava/lang/String;)V
            // (LSystem/String;LSystem/String;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ClassLib.CommunicationManager @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ClassLib.CommunicationManager>(@__env, @__obj);
            @__real.AddNewSubscriptionClient(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, priorityId), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, subscriptionName));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle RemoveStreamingSubscriptionClientAsync8(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle contentIdentification, global::net.sf.jni4net.utils.JniLocalHandle streamerTopicName) {
            // (Ljava/lang/String;Ljava/lang/String;)Lsystem/Object;
            // (LSystem/String;LSystem/String;)LSystem/Threading/Tasks/Task;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ClassLib.CommunicationManager @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ClassLib.CommunicationManager>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Threading.Tasks.Task>(@__env, @__real.RemoveStreamingSubscriptionClientAsync(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, contentIdentification), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, streamerTopicName)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void InitLogSystem9(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ClassLib.CommunicationManager @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ClassLib.CommunicationManager>(@__env, @__obj);
            @__real.InitLogSystem();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void InitLogSystem10(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle path) {
            // (Ljava/lang/String;)V
            // (LSystem/String;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ClassLib.CommunicationManager @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ClassLib.CommunicationManager>(@__env, @__obj);
            @__real.InitLogSystem(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, path));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle BaseTopicToId11(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle topicName) {
            // (Ljava/lang/String;)Ljava/lang/String;
            // (LSystem/String;)LSystem/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2JString(@__env, global::ClassLib.CommunicationManager.BaseTopicToId(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, topicName)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void @__ctorCommunicationManager0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle serviceBusClientId, global::net.sf.jni4net.utils.JniLocalHandle topicsConfiguration, global::net.sf.jni4net.utils.JniLocalHandle callbacksInterface) {
            // (Ljava/lang/String;Lclasslib/TopicsConfiguration;Lclasslib/ICommunicationManagerCallbacks;)V
            // (LSystem/String;LClassLib/TopicsConfiguration;LClassLib/ICommunicationManagerCallbacks;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ClassLib.CommunicationManager @__real = new global::ClassLib.CommunicationManager(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, serviceBusClientId), global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ClassLib.TopicsConfiguration>(@__env, topicsConfiguration), global::net.sf.jni4net.utils.Convertor.FullJ2C<global::ClassLib.ICommunicationManagerCallbacks>(@__env, callbacksInterface));
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::ClassLib.@__CommunicationManager(@__env);
            }
        }
    }
    #endregion
}
