//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLib {
    
    
    #region Component Designer generated code 
    public partial class ServiceBusManager_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::ClassLib.@__ServiceBusManager.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::ClassLib.ServiceBusManager), typeof(global::ClassLib.ServiceBusManager_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::ClassLib.ServiceBusManager), typeof(global::ClassLib.ServiceBusManager_))]
    internal sealed partial class @__ServiceBusManager : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__ServiceBusManager(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::ClassLib.@__ServiceBusManager.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__ServiceBusManager);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "CreateDefaultSubscriptionAsync", "CreateDefaultSubscriptionAsync0", "(Ljava/lang/String;Ljava/lang/String;)Lsystem/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "CreateStreamingContentSubscriptionAsync", "CreateStreamingContentSubscriptionAsync1", "(Ljava/lang/String;Ljava/lang/String;Lclasslib/ClientTopicsInfo;)Lsystem/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "DeleteStreamingContentSubscriptionAsync", "DeleteStreamingContentSubscriptionAsync2", "(Ljava/lang/String;Ljava/lang/String;Lclasslib/ClientTopicsInfo;)Lsystem/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "AddSubscriptionRuleAsync", "AddSubscriptionRuleAsync3", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lclassli" +
                        "b/ClientTopicsInfo;)Lsystem/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "RemoveSubscriptionRuleAsync", "RemoveSubscriptionRuleAsync4", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lsystem/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "CreateTopicAsync", "CreateTopicAsync5", "(Ljava/lang/String;)Lsystem/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "DeleteDefaultSubscriptionAsync", "DeleteDefaultSubscriptionAsync6", "(Lclasslib/ClientTopicsInfo;)Lsystem/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "DeleteTopicAsync", "DeleteTopicAsync7", "(Ljava/lang/String;)Lsystem/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "CreatePrioritySubscriptionsAsync", "CreatePrioritySubscriptionsAsync8", "(ILclasslib/ClientTopicsInfo;)Lsystem/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "DeleteExtraPrioritySubscriptions", "DeleteExtraPrioritySubscriptions9", "(Lclasslib/ClientTopicsInfo;I)Lsystem/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetPriorityExclusionSqlExpression", "GetPriorityExclusionSqlExpression10", "(I)Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorServiceBusManager0", "__ctorServiceBusManager0", "(Lnet/sf/jni4net/inj/IClrProxy;Lclasslib/TopicsConfiguration;Ljava/lang/String;)V" +
                        ""));
            return methods;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle CreateDefaultSubscriptionAsync0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle topicName, global::net.sf.jni4net.utils.JniLocalHandle subscriptionName) {
            // (Ljava/lang/String;Ljava/lang/String;)Lsystem/Object;
            // (LSystem/String;LSystem/String;)LSystem/Threading/Tasks/Task;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ClassLib.ServiceBusManager @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ClassLib.ServiceBusManager>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Threading.Tasks.Task>(@__env, @__real.CreateDefaultSubscriptionAsync(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, topicName), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, subscriptionName)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle CreateStreamingContentSubscriptionAsync1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle contentIdentification, global::net.sf.jni4net.utils.JniLocalHandle streamerTopicName, global::net.sf.jni4net.utils.JniLocalHandle clientInfo) {
            // (Ljava/lang/String;Ljava/lang/String;Lclasslib/ClientTopicsInfo;)Lsystem/Object;
            // (LSystem/String;LSystem/String;LClassLib/ClientTopicsInfo;)LSystem/Threading/Tasks/Task;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ClassLib.ServiceBusManager @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ClassLib.ServiceBusManager>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Threading.Tasks.Task>(@__env, @__real.CreateStreamingContentSubscriptionAsync(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, contentIdentification), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, streamerTopicName), global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ClassLib.ClientTopicsInfo>(@__env, clientInfo)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle DeleteStreamingContentSubscriptionAsync2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle contentIdentification, global::net.sf.jni4net.utils.JniLocalHandle streamerTopicName, global::net.sf.jni4net.utils.JniLocalHandle clientInfo) {
            // (Ljava/lang/String;Ljava/lang/String;Lclasslib/ClientTopicsInfo;)Lsystem/Object;
            // (LSystem/String;LSystem/String;LClassLib/ClientTopicsInfo;)LSystem/Threading/Tasks/Task;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ClassLib.ServiceBusManager @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ClassLib.ServiceBusManager>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Threading.Tasks.Task>(@__env, @__real.DeleteStreamingContentSubscriptionAsync(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, contentIdentification), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, streamerTopicName), global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ClassLib.ClientTopicsInfo>(@__env, clientInfo)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle AddSubscriptionRuleAsync3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle topicName, global::net.sf.jni4net.utils.JniLocalHandle subscriptionName, global::net.sf.jni4net.utils.JniLocalHandle ruleName, global::net.sf.jni4net.utils.JniLocalHandle sqlFilter, global::net.sf.jni4net.utils.JniLocalHandle clientInfo) {
            // (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lclasslib/ClientTopicsInfo;)Lsystem/Object;
            // (LSystem/String;LSystem/String;LSystem/String;LSystem/String;LClassLib/ClientTopicsInfo;)LSystem/Threading/Tasks/Task;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ClassLib.ServiceBusManager @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ClassLib.ServiceBusManager>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Threading.Tasks.Task>(@__env, @__real.AddSubscriptionRuleAsync(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, topicName), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, subscriptionName), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, ruleName), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, sqlFilter), global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ClassLib.ClientTopicsInfo>(@__env, clientInfo)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle RemoveSubscriptionRuleAsync4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle topicName, global::net.sf.jni4net.utils.JniLocalHandle subscriptionName, global::net.sf.jni4net.utils.JniLocalHandle ruleName) {
            // (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lsystem/Object;
            // (LSystem/String;LSystem/String;LSystem/String;)LSystem/Threading/Tasks/Task;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ClassLib.ServiceBusManager @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ClassLib.ServiceBusManager>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Threading.Tasks.Task>(@__env, @__real.RemoveSubscriptionRuleAsync(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, topicName), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, subscriptionName), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, ruleName)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle CreateTopicAsync5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle topicName) {
            // (Ljava/lang/String;)Lsystem/Object;
            // (LSystem/String;)LSystem/Threading/Tasks/Task;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ClassLib.ServiceBusManager @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ClassLib.ServiceBusManager>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Threading.Tasks.Task>(@__env, @__real.CreateTopicAsync(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, topicName)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle DeleteDefaultSubscriptionAsync6(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle clientInfo) {
            // (Lclasslib/ClientTopicsInfo;)Lsystem/Object;
            // (LClassLib/ClientTopicsInfo;)LSystem/Threading/Tasks/Task;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ClassLib.ServiceBusManager @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ClassLib.ServiceBusManager>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Threading.Tasks.Task>(@__env, @__real.DeleteDefaultSubscriptionAsync(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ClassLib.ClientTopicsInfo>(@__env, clientInfo)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle DeleteTopicAsync7(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle topicName) {
            // (Ljava/lang/String;)Lsystem/Object;
            // (LSystem/String;)LSystem/Threading/Tasks/Task;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ClassLib.ServiceBusManager @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ClassLib.ServiceBusManager>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Threading.Tasks.Task>(@__env, @__real.DeleteTopicAsync(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, topicName)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle CreatePrioritySubscriptionsAsync8(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int totalNumberOfPriorityLevels, global::net.sf.jni4net.utils.JniLocalHandle clientInfo) {
            // (ILclasslib/ClientTopicsInfo;)Lsystem/Object;
            // (ILClassLib/ClientTopicsInfo;)LSystem/Threading/Tasks/Task;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ClassLib.ServiceBusManager @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ClassLib.ServiceBusManager>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Threading.Tasks.Task>(@__env, @__real.CreatePrioritySubscriptionsAsync(totalNumberOfPriorityLevels, global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ClassLib.ClientTopicsInfo>(@__env, clientInfo)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle DeleteExtraPrioritySubscriptions9(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle clientInfo, int numberOfPriorityLevels) {
            // (Lclasslib/ClientTopicsInfo;I)Lsystem/Object;
            // (LClassLib/ClientTopicsInfo;I)LSystem/Threading/Tasks/Task;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ClassLib.ServiceBusManager @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ClassLib.ServiceBusManager>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Threading.Tasks.Task>(@__env, @__real.DeleteExtraPrioritySubscriptions(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ClassLib.ClientTopicsInfo>(@__env, clientInfo), numberOfPriorityLevels));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle GetPriorityExclusionSqlExpression10(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int numberOfPriorityLevels) {
            // (I)Ljava/lang/String;
            // (I)LSystem/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::ClassLib.ServiceBusManager @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ClassLib.ServiceBusManager>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2JString(@__env, @__real.GetPriorityExclusionSqlExpression(numberOfPriorityLevels));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void @__ctorServiceBusManager0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle topicsConfiguration, global::net.sf.jni4net.utils.JniLocalHandle connectionString) {
            // (Lclasslib/TopicsConfiguration;Ljava/lang/String;)V
            // (LClassLib/TopicsConfiguration;LSystem/String;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ClassLib.ServiceBusManager @__real = new global::ClassLib.ServiceBusManager(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::ClassLib.TopicsConfiguration>(@__env, topicsConfiguration), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, connectionString));
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::ClassLib.@__ServiceBusManager(@__env);
            }
        }
    }
    #endregion
}
