//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLib {
    
    
    #region Component Designer generated code 
    public partial class TopicsConfiguration_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::ClassLib.@__TopicsConfiguration.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::ClassLib.TopicsConfiguration), typeof(global::ClassLib.TopicsConfiguration_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::ClassLib.TopicsConfiguration), typeof(global::ClassLib.TopicsConfiguration_))]
    internal sealed partial class @__TopicsConfiguration : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__TopicsConfiguration(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::ClassLib.@__TopicsConfiguration.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__TopicsConfiguration);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorTopicsConfiguration0", "__ctorTopicsConfiguration0", "(Lnet/sf/jni4net/inj/IClrProxy;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorTopicsConfiguration1", "__ctorTopicsConfiguration1", "(Lnet/sf/jni4net/inj/IClrProxy;IIII)V"));
            return methods;
        }
        
        private static void @__ctorTopicsConfiguration0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ClassLib.TopicsConfiguration @__real = new global::ClassLib.TopicsConfiguration();
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorTopicsConfiguration1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int messageMaxTimeToLive, int topicAutoDeleteOnIdleTime, int maxDeliveryCount, int numberOfPriorityLevels) {
            // (IIII)V
            // (IIII)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::ClassLib.TopicsConfiguration @__real = new global::ClassLib.TopicsConfiguration(messageMaxTimeToLive, topicAutoDeleteOnIdleTime, maxDeliveryCount, numberOfPriorityLevels);
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::ClassLib.@__TopicsConfiguration(@__env);
            }
        }
    }
    #endregion
}
