// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package classlib;

@net.sf.jni4net.attributes.ClrType
public class BusMessage extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected BusMessage(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("(LSystem/String;LSystem/String;LSystem/String;LSystem/String;LSystem/String;LSystem/String;LSystem/String;LSystem/String;)V")
    public BusMessage(java.lang.String id, java.lang.String messageType, java.lang.String infoIdentifier, java.lang.String toTopic, java.lang.String fromTopic, java.lang.String dataFormat, java.lang.String content, java.lang.String priority) {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        classlib.BusMessage.__ctorBusMessage0(this, id, messageType, infoIdentifier, toTopic, fromTopic, dataFormat, content, priority);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("(LSystem/String;LSystem/String;LSystem/String;LSystem/String;LSystem/String;LSystem/String;LSystem/String;LSystem/String;J)V")
    public BusMessage(java.lang.String id, java.lang.String messageType, java.lang.String infoIdentifier, java.lang.String toTopic, java.lang.String fromTopic, java.lang.String dataFormat, java.lang.String content, java.lang.String priority, long enqueuedTime) {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        classlib.BusMessage.__ctorBusMessage1(this, id, messageType, infoIdentifier, toTopic, fromTopic, dataFormat, content, priority, enqueuedTime);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V")
    private native static void __ctorBusMessage0(net.sf.jni4net.inj.IClrProxy thiz, java.lang.String id, java.lang.String messageType, java.lang.String infoIdentifier, java.lang.String toTopic, java.lang.String fromTopic, java.lang.String dataFormat, java.lang.String content, java.lang.String priority);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;J)V")
    private native static void __ctorBusMessage1(net.sf.jni4net.inj.IClrProxy thiz, java.lang.String id, java.lang.String messageType, java.lang.String infoIdentifier, java.lang.String toTopic, java.lang.String fromTopic, java.lang.String dataFormat, java.lang.String content, java.lang.String priority, long enqueuedTime);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getId();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getMessageType();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getInfoIdentifier();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getToTopic();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getFromTopic();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getDataFormat();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getContent();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getPriority();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setPriority(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()J")
    public native long getEnqueuedTime();
    
    @net.sf.jni4net.attributes.ClrMethod("(J)V")
    public native void setEnqueuedTime(long value);
    
    public static system.Type typeof() {
        return classlib.BusMessage.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        classlib.BusMessage.staticType = staticType;
    }
    //</generated-proxy>
}
