// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package classlib;

@net.sf.jni4net.attributes.ClrType
public class MessagePriorityManager extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected MessagePriorityManager(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("(ILClassLib/ICommunicationManagerCallbacks;)V")
    public MessagePriorityManager(int numberOfPriorityLevels, classlib.ICommunicationManagerCallbacks callbacksInterface) {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        classlib.MessagePriorityManager.__ctorMessagePriorityManager0(this, numberOfPriorityLevels, callbacksInterface);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(ILclasslib/ICommunicationManagerCallbacks;)V")
    private native static void __ctorMessagePriorityManager0(net.sf.jni4net.inj.IClrProxy thiz, int numberOfPriorityLevels, classlib.ICommunicationManagerCallbacks callbacksInterface);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void ListenForMessages();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LClassLib/BusMessage;)V")
    public native void AddMessageToList(java.lang.String priorityOfTheList, classlib.BusMessage message);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void ProcessCriticalMessage();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void CreateNewMessageList(java.lang.String priority);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void RemoveMessageList(java.lang.String priorityId);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String GetLowestPriorityLevel();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native static void CheckPriority(java.lang.String priority);
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    public native static void CheckNumberOfPriorityLevels(int numberOfPriorityLevels);
    
    public static system.Type typeof() {
        return classlib.MessagePriorityManager.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        classlib.MessagePriorityManager.staticType = staticType;
    }
    //</generated-proxy>
}
