// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package classlib;

@net.sf.jni4net.attributes.ClrType
public class ServiceBusManager extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected ServiceBusManager(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("(LClassLib/TopicsConfiguration;LSystem/String;)V")
    public ServiceBusManager(classlib.TopicsConfiguration topicsConfiguration, java.lang.String connectionString) {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        classlib.ServiceBusManager.__ctorServiceBusManager0(this, topicsConfiguration, connectionString);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(Lclasslib/TopicsConfiguration;Ljava/lang/String;)V")
    private native static void __ctorServiceBusManager0(net.sf.jni4net.inj.IClrProxy thiz, classlib.TopicsConfiguration topicsConfiguration, java.lang.String connectionString);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LSystem/String;)LSystem/Threading/Tasks/Task;")
    public native system.Object CreateDefaultSubscriptionAsync(java.lang.String topicName, java.lang.String subscriptionName);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LSystem/String;LClassLib/ClientTopicsInfo;)LSystem/Threading/Tasks/Task;")
    public native system.Object CreateStreamingContentSubscriptionAsync(java.lang.String contentIdentification, java.lang.String streamerTopicName, classlib.ClientTopicsInfo clientInfo);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LSystem/String;LClassLib/ClientTopicsInfo;)LSystem/Threading/Tasks/Task;")
    public native system.Object DeleteStreamingContentSubscriptionAsync(java.lang.String contentIdentification, java.lang.String streamerTopicName, classlib.ClientTopicsInfo clientInfo);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LSystem/String;LSystem/String;LSystem/String;LClassLib/ClientTopicsInfo;)LSystem/Threading/Tasks/Task;")
    public native system.Object AddSubscriptionRuleAsync(java.lang.String topicName, java.lang.String subscriptionName, java.lang.String ruleName, java.lang.String sqlFilter, classlib.ClientTopicsInfo clientInfo);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LSystem/String;LSystem/String;)LSystem/Threading/Tasks/Task;")
    public native system.Object RemoveSubscriptionRuleAsync(java.lang.String topicName, java.lang.String subscriptionName, java.lang.String ruleName);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)LSystem/Threading/Tasks/Task;")
    public native system.Object CreateTopicAsync(java.lang.String topicName);
    
    @net.sf.jni4net.attributes.ClrMethod("(LClassLib/ClientTopicsInfo;)LSystem/Threading/Tasks/Task;")
    public native system.Object DeleteDefaultSubscriptionAsync(classlib.ClientTopicsInfo clientInfo);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)LSystem/Threading/Tasks/Task;")
    public native system.Object DeleteTopicAsync(java.lang.String topicName);
    
    @net.sf.jni4net.attributes.ClrMethod("(ILClassLib/ClientTopicsInfo;)LSystem/Threading/Tasks/Task;")
    public native system.Object CreatePrioritySubscriptionsAsync(int totalNumberOfPriorityLevels, classlib.ClientTopicsInfo clientInfo);
    
    @net.sf.jni4net.attributes.ClrMethod("(LClassLib/ClientTopicsInfo;I)LSystem/Threading/Tasks/Task;")
    public native system.Object DeleteExtraPrioritySubscriptions(classlib.ClientTopicsInfo clientInfo, int numberOfPriorityLevels);
    
    @net.sf.jni4net.attributes.ClrMethod("(I)LSystem/String;")
    public native java.lang.String GetPriorityExclusionSqlExpression(int numberOfPriorityLevels);
    
    public static system.Type typeof() {
        return classlib.ServiceBusManager.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        classlib.ServiceBusManager.staticType = staticType;
    }
    //</generated-proxy>
}
