// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package classlib;

@net.sf.jni4net.attributes.ClrType
public class Util extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected Util(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    protected Util() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native static boolean getPrintErrorMessages();
    
    @net.sf.jni4net.attributes.ClrMethod("(Z)V")
    public native static void setPrintErrorMessages(boolean value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native static java.lang.String GenerateId();
    
    @net.sf.jni4net.attributes.ClrMethod("()J")
    public native static long GetCurrentTimeInMillis();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native static void PrintErrorMessage(java.lang.String message);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native static java.lang.String GetProjectPath();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native static java.lang.String GetCurrentTimeAndDate();
    
    public static system.Type typeof() {
        return classlib.Util.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        classlib.Util.staticType = staticType;
    }
    //</generated-proxy>
}
